Homework ruslan lesson8
yuriy-tsarenko/java_essential pull request #22
Opened 2021-05-16 19:50 UTC by Svitliy

2021-05-17 21:32 UTC, ochedenis submitted a review, later dismissed

2021-05-17 21:32 UTC, ochedenis commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson8/task2/Main.java
> +        }
Можно обойтись одним try-catch.
finally должна быть на той же строке, что и закрывающая скобка try-catch.
![image](https://user-images.githubusercontent.com/22505483/118559320-6b56c180-b770-11eb-8f36-8480d771c1c6.png)

2021-05-18 09:29 UTC, yuriy-tsarenko requested changes
пофиксите комменты

2021-05-18 09:29 UTC, yuriy-tsarenko commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson8/task2/Main.java
> +                (new InputStreamReader(System.in));
```suggestion
               BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
```
переместите в одну строку

2021-05-18 09:29 UTC, yuriy-tsarenko commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson8/task2/Main.java
> +
```suggestion
// создайте метод и вызывайте в мейне в цикле
     for (int i = 0; i < workers.length; i++) {
            try {
                createWorker(workerNew);
            } catch (IOException e) {
                System.err.println("некорректный ввод!!!\nповторите еще раз");
                log.warn(e);
            }
        }
 //
        private static Worker createWorker(Worker workerNew) throws IOException {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));

        System.out.println("Введите ФИО: ");

        workerNew.setInitials(reader.readLine());

        System.out.println("Введите должность: ");

        workerNew.setPosition(reader.readLine());

        System.out.println("Введите год приема: ");

        workerNew.setYear(reader.readLine());

        isDateValid(workerNew.getYear());

        reader.close();

        return workerNew;
    }
```

2021-05-19 09:30 UTC, yuriy-tsarenko reviewed
пофиксите использование трай кеч конструкций

2021-05-19 09:30 UTC, yuriy-tsarenko commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson8/task2/Main.java
> +
создайте метод и вызывайте в мейне в цикле, это плохая практика использовать такое большое количество трай кеч блоков
```suggestion
 // создайте метод и вызывайте в мейне в цикле
     for (int i = 0; i < workers.length; i++) {
        try {
            createWorker(workerNew);
        } catch (IOException e) {
            System.err.println("некорректный ввод!!!\nповторите еще раз");
            log.warn(e);
        }
    }
    //
    private static Worker createWorker(Worker workerNew) throws IOException {
        BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("Введите ФИО: ");
        workerNew.setInitials(reader.readLine());
        System.out.println("Введите должность: ");
        workerNew.setPosition(reader.readLine());
        System.out.println("Введите год приема: ");
        workerNew.setYear(reader.readLine());
        isDateValid(workerNew.getYear());
        reader.close();
        return workerNew;
    }
```

2021-06-01 06:51 UTC, merged