Homework ruslan lesson9
yuriy-tsarenko/java_essential pull request #33
Opened 2021-05-22 14:12 UTC by Svitliy

2021-05-24 09:29 UTC, ochedenis requested changes

2021-05-24 09:29 UTC, ochedenis commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson9/task4/Device.java
> +class EthernetAdapter {
К чему вам этот класс, если его нигде не используете?

2021-05-24 09:29 UTC, ochedenis commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson9/task3/Device.java
> +class EthernetAdapter {
К чему вам этот класс, если его нигде не используете?

2021-05-24 09:29 UTC, ochedenis commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson9/task2/Device.java
> +    EthernetAdapter(int speed, String mac) {
К чему вам этот класс, если его нигде не используете?

2021-05-24 15:35 UTC, Svitliy commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson9/task2/Device.java
> +    EthernetAdapter(int speed, String mac) {
Такие требования условия задания!
Задание 2
Создать классы: 1) Основной класс Device (manufacturer(String), price(float), serialNumber(String));
 2) Сабкалсс Monitor (resolutionX(int), resolutionY(int)) 
and **_EthernetAdapter (speed (int), mac (String))_**; Добавить методы доступа. Конструктор.

2021-06-01 07:27 UTC, yuriy-tsarenko requested changes

2021-06-01 07:27 UTC, yuriy-tsarenko commented on src/main/java/com/cbs/java_essential/ruslan/homework/lesson9/addtask/Animal.java
> +    }
Переделайте метод:
1. конструкция if-else должна быть согласно code conventions
 https://www.oracle.com/java/technologies/javase/codeconventions-contents.html
2. переопределите метод согласно примеру с занятия и старайтесь в return не добавлять много кода, ориентируйтесь на возможность расширения кода, представьте, если у класса будет двадцать полей

2021-06-01 08:16 UTC, merged