Homework dikalo lesson1
yuriy-tsarenko/java_essential pull request #6
Opened 2021-04-24 18:35 UTC by yurii-dikalo

2021-04-29 14:30 UTC, ochedenis approved these changes, later dismissed

2021-05-18 08:46 UTC, yuriy-tsarenko requested changes
из фиксом для мавен билда, удалите один класс, я его отметил

2021-05-18 08:46 UTC, yuriy-tsarenko commented on src/main/java/com/cbs/java_essential/dikalo/homework/Test.java
> +public class Test {
Удалите этот класс

2021-05-19 09:32 UTC, yuriy-tsarenko reviewed
Зачем lesson2 добавлять в ветку с lesson1, разделите и создайте отдельный пул реквест, а отсюда уберите

2021-06-01 06:31 UTC, merged